server:
  port: 8081

spring:
  application:
    name: order-service

management:
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
      transport: http
    metrics:
      export:
        enabled: false

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"